version: '3'
services:
  train_DCGAN:
    image: 'minamotofordocker/pokemon_generator:latest'
    container_name: 'pokemon_generator'
    volumes:
      - $PWD:/PokemonGenerator
    stdin_open: true
    tty: true
    working_dir: /PokemonGenerator
    # GPU Setting
    # runtime: nvidia
    # environment:
    #   - NVIDIA_VISIBLE_DEVICES=all
    # python DCGAN-tensorflow/main.py
    command: python DCGAN-tensorflow-pokemon/main.py --data_dir data/ --dataset pokemon_image --out_dir out/ --out_name pokemon_gan_sample --input_fname_pattern=*.png --input_height 120 --output_height 120 --train --epoch=5000 --batch_size=64 --learning_rate=0.001 --G_img_sum
